name: Render documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[all]
    - name: Render the documentation
      run: >
        sphinx-build
        -M html ./doc ./build/sphinx
        -vv
        --jobs=auto
        --show-traceback
        # --fail-on-warning
        --keep-going
